import type { Metadata } from "next";
import { Inter, League_Gothic } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/utils/lenis";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const league = League_Gothic({
  variable: "--font-league-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kabu - Ecommerce Store Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${league.variable} antialiased`}
      >
        <ReactLenis root>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
